# Generated by Django 5.2.4 on 2025-08-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sho', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_in_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
