# Generated by Django 5.2.4 on 2025-08-04 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sho', '0003_productreview_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='color',
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sho.product'),
            preserve_default=False,
        ),
    ]
