# Generated by Django 5.2.4 on 2025-08-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sho', '0004_remove_productreview_color_productreview_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='review_image',
            field=models.ImageField(default=1, upload_to='review_images'),
            preserve_default=False,
        ),
    ]
