# Generated by Django 5.2.4 on 2025-08-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sho', '0005_productreview_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
