# Generated by Django 5.2.4 on 2025-08-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sho', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
