# Generated by Django 5.2.4 on 2025-08-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sho', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='redeemed_points',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
