# Generated by Django 5.2.4 on 2025-08-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sho', '0011_orderitem_redeemed_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='redeemed_points',
        ),
        migrations.AddField(
            model_name='order',
            name='redeemed_points',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
